version: '3.8'

services:
  db:
    image: mysql:5.7 # ou outro banco de dados SQL de sua escolha
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
