version: '3.8'

services:
  api:
    build: ./api
    env_file:
      - .env
    volumes:
      - ./api:/go/src/app
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:5.7 # ou outro banco de dados SQL de sua escolha
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: